# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='prob_popular',
            field=models.BooleanField(default=False),
        ),
    ]
