# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_name', models.TextField(max_length=1000)),
                ('prob_statement', models.TextField(max_length=1000)),
                ('prob_support', models.TextField(max_length=1000)),
                ('prob_comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='prob_sources',
            field=models.ManyToManyField(to='algo_app.Source'),
        ),
        migrations.AddField(
            model_name='problem',
            name='prob_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo_app.Type'),
        ),
    ]
