# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0002_auto_20170511_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.CharField(max_length=255)),
                ('event_time', models.CharField(max_length=255)),
                ('event_location', models.TextField(max_length=1000)),
                ('event_comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algo_app.User')),
            ],
        ),
    ]
